# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/b83c/fpga/rv32/ips/clk_mcmm/clk_mcmm.xci
# IP: The module: 'clk_mcmm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/b83c/fpga/rv32/ips/clk_mcmm/clk_mcmm_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_mcmm'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/b83c/fpga/rv32/ips/clk_mcmm/clk_mcmm.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_mcmm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/b83c/fpga/rv32/ips/clk_mcmm/clk_mcmm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_mcmm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/b83c/fpga/rv32/ips/clk_mcmm/clk_mcmm.xci
# IP: The module: 'clk_mcmm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/b83c/fpga/rv32/ips/clk_mcmm/clk_mcmm_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_mcmm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/b83c/fpga/rv32/ips/clk_mcmm/clk_mcmm.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_mcmm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/b83c/fpga/rv32/ips/clk_mcmm/clk_mcmm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_mcmm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
